const constants = {
    EDIT_LIST_TITLE: "EDIT_LIST_TITLE",
    EDIT_CARD_TITLE: "EDIT_CARD_TITLE",
    EDIT_CARD_DESCRIPTION: "EDIT_CARD_DESCRIPTION",
    ADD_COMMENT: "ADD_COMMENT",
    DELETE_COMMENT: "DELETE_COMMENT",
    ADD_CARD: "ADD_CARD",
    ADD_LIST: "ADD_LIST",
    COPY_LIST: "COPY_LIST",
    MOVE_LIST: "MOVE_LIST",
    MOVE_CARD: "MOVE_CARD",
    CHANGE_LIST: "CHANGE_LIST",
    ARCHIVE_LIST: "ARCHIVE_LIST",
    ARCHIVE_ALL_CARDS: "ARCHIVE_ALL_CARDS",
    ARCHIVE_CARD: "ARCHIVE_CARD",
    MOVE_ALL_CARDS: "MOVE_ALL_CARDS"
};

export default constants;
/* To be implemented 

EDIT_LABELS: "EDIT_LABELS",
CHANGE_MEMBERS: "CHANGE_MEMBERS",
CHANGE_DUE_DATE: "CHANGE_DUE_DATE ",
ARCHIVE: "ARCHIVE"

*/
